name: cc04
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+3
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  sqflite: ^1.3.0
  path_provider: ^1.6.7
  uuid: ^2.0.4
  json_annotation: ^3.0.1
  rxdart: ^0.24.0
  dialog_information_to_specific_platform: ^0.0.4
  flare_flutter: ^2.0.3
  mobx: ^1.1.1
  get_it: ^4.0.2
  flutter_mobx: ^1.1.0
  giffy_dialog: ^1.7.0

dev_dependencies:
  build_runner: ^1.9.0
  json_serializable: ^3.3.0
  mobx_codegen: ^1.0.3
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5

flutter_native_splash:
  image: assets/images/launchscreen.png
  color: "336699"

flutter_icons:
  image_path: "assets/images/launchscreen.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/drawer/
    - assets/images/jogo/
    - assets/flare/
    - assets/gifs/
    - assets/images/splashscreen.png
