name: capitulo03_splashscreen
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  cupertino_icons: ^1.0.2
  dialog_information_to_specific_platform: ^0.0.7
  equatable: ^2.0.3
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_mobx: ^2.0.6+1
  get_it: ^7.2.0
  json_annotation: ^4.4.0
  mobx: ^2.0.7+2
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2+1
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.2.2
  giff_dialog: ^1.0.1
  icons_launcher: ^1.1.9
  json_serializable: ^6.1.6
  mobx_codegen: ^2.0.7

flutter_native_splash:
  image: assets/images/launchscreen.png
  color: "336699"
  
flutter_icons:
  image_path: "assets/images/launchscreen.png"
  android: true
  ios: true
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/splashscreen.png
    - assets/images/drawer/
    - assets/images/jogo/
    - assets/flare/
    - assets/gifs/